name: MSBuild

on:
  push:
    paths:
    - '.github/workflows/build.yml'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: cmake bulid 
#       working-directory: c:\vcpkg
      run: |
        mkdir build && cd build
        cmake .. 
        echo "cmake --build . --config " ${BUILD_CONFIGURATION}
        cmake --build . --config ${BUILD_TYPE}
        
    
